### PR TITLE
35/issue template forms

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Part of #35 

Adding issue template forms:

- Add token
- Remove token
- Add image

For more info, see GH's docs on [templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) and the [form syntax](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema)

# Testing

Not possible to test until this is merged to `main`

### CODE REVIEW

**Comment by alfetopito** [comment]
Please post merge review

**Comment by anxolin** [comment]
Post-merge review :) 

This is super cool!

Only concern, since we do some things programmatically, should we not ask for the derived information? Like symbols, decimals, name will be derived form the address. Or this is just because we will save some time with the implementation? 

image

**Comment by anxolin** [comment]
For the images, you will post-process to optimize, right? 

If so, why limiting the input to an image in IPFS. Should we allow to input any URL, and maybe provide a hint on how to upload it if they only have it locally? (like a simple service where they can drag and drop the image and get the URL


image

**Comment by alfetopito** [comment]
> since we do some things programmatically, should we not ask for the derived information? Like symbols, decimals, name will be derived form the address. Or this is just because we will save some time with the implementation?

For that kind of info, we'd have to either get the info from onchain directly (more trustworthy) use a 3rd party api service.
For the former, not sure how feasible that is to do from within a github action.
For the later, I feel like it's just an extra step to adding it manually and we would have to trust the API info in correct.

I think for now requiring manual input is fine. We can re-iterate but I prefer to start like this

> If so, why limiting the input to an image in IPFS. Should we allow to input any URL, and maybe provide a hint on how to upload it if they only have it locally? (like a simple service where they can drag and drop the image and get the URL

Great idea, I haven't thought of that. Will update

**Comment by alfetopito** [comment]
@anxolin https://github.com/cowprotocol/token-lists/pull/48

**Pull request merged**
